[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true
